baseURL = "/"
languageCode = "en-us"
title = "Caleb Schoepp"
theme = "caleb-www-theme"
googleAnalytics = "UA-129268689-2"
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "manni"
    tabWidth = 4
  # Add this to make shortcodes render html correctly
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
