baseURL = "calebschoepp.com"
languageCode = "en-us"
title = "Caleb Schoepp"
theme = "caleb-www-theme"
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "manni"
    tabWidth = 4
